export const generatedPortfolioItems = [
      {
        id: "yt-pFI-M5TxjlE",
        category: "유튜브",
        title: "송유헤어 홍보ver.",
        client: "Try to 신감독",
        image: "https://img.youtube.com/vi/pFI-M5TxjlE/hqdefault.jpg",
        duration: "0:31",
        videoType: "youtube",
        youtubeUrl: "https://www.youtube.com/watch?v=pFI-M5TxjlE",
        videoUrl: "",
      },
      {
        id: "yt-lFLvAPj3JGo",
        category: "유튜브",
        title: "아우 시끄러워",
        client: "Try to 신감독",
        image: "https://img.youtube.com/vi/lFLvAPj3JGo/hqdefault.jpg",
        duration: "4:39",
        videoType: "youtube",
        youtubeUrl: "https://www.youtube.com/watch?v=lFLvAPj3JGo",
        videoUrl: "",
      },
      {
        id: "yt-GKy-AyXZx2Y",
        category: "유튜브",
        title: "서촌 카페 폴키 아기자기 ver",
        client: "Try to 신감독",
        image: "https://img.youtube.com/vi/GKy-AyXZx2Y/hqdefault.jpg",
        duration: "0:52",
        videoType: "youtube",
        youtubeUrl: "https://www.youtube.com/watch?v=GKy-AyXZx2Y",
        videoUrl: "",
      },
      {
        id: "yt-Odmg6U_-XGY",
        category: "유튜브",
        title: "서촌 카페 폴키 무드 ver",
        client: "Try to 신감독",
        image: "https://img.youtube.com/vi/Odmg6U_-XGY/hqdefault.jpg",
        duration: "0:31",
        videoType: "youtube",
        youtubeUrl: "https://www.youtube.com/watch?v=Odmg6U_-XGY",
        videoUrl: "",
      },
      {
        id: "yt-ILUaPPROomU",
        category: "유튜브",
        title: "서촌 카페 폴키 매장 홍보영상 공간_ver",
        client: "Try to 신감독",
        image: "https://img.youtube.com/vi/ILUaPPROomU/hqdefault.jpg",
        duration: "0:17",
        videoType: "youtube",
        youtubeUrl: "https://www.youtube.com/watch?v=ILUaPPROomU",
        videoUrl: "",
      },
      {
        id: "yt-1CUt84BK_p0",
        category: "유튜브",
        title: "패션을 파는 것은 어떨까요?",
        client: "Try to 신감독",
        image: "https://img.youtube.com/vi/1CUt84BK_p0/hqdefault.jpg",
        duration: "0:53",
        videoType: "youtube",
        youtubeUrl: "https://www.youtube.com/watch?v=1CUt84BK_p0",
        videoUrl: "",
      },
      {
        id: "yt-__Jx8hdRy3w",
        category: "유튜브",
        title: "이 영상은 우지커피 광고 영상입니다.",
        client: "Try to 신감독",
        image: "https://img.youtube.com/vi/__Jx8hdRy3w/hqdefault.jpg",
        duration: "1:40",
        videoType: "youtube",
        youtubeUrl: "https://www.youtube.com/watch?v=__Jx8hdRy3w",
        videoUrl: "",
      },
      {
        id: "yt-gaGXwv9O2CU",
        category: "유튜브",
        title: "더울 땐 \"우지커피\"",
        client: "Try to 신감독",
        image: "https://img.youtube.com/vi/gaGXwv9O2CU/hqdefault.jpg",
        duration: "0:31",
        videoType: "youtube",
        youtubeUrl: "https://www.youtube.com/watch?v=gaGXwv9O2CU",
        videoUrl: "",
      },
      {
        id: "yt-HO5160gY5ko",
        category: "유튜브",
        title: "TRY TO 신감독입니다.",
        client: "Try to 신감독",
        image: "https://img.youtube.com/vi/HO5160gY5ko/hqdefault.jpg",
        duration: "0:53",
        videoType: "youtube",
        youtubeUrl: "https://www.youtube.com/watch?v=HO5160gY5ko",
        videoUrl: "",
      },
      {
        id: "yt-YQqDmINaEKo",
        category: "유튜브",
        title: "이분.. 일타강사가 될 것 같아요",
        client: "Try to 신감독",
        image: "https://img.youtube.com/vi/YQqDmINaEKo/hqdefault.jpg",
        duration: "13:37",
        videoType: "youtube",
        youtubeUrl: "https://www.youtube.com/watch?v=YQqDmINaEKo",
        videoUrl: "",
      },
      {
        id: "yt-Di-6xXKzmN8",
        category: "유튜브",
        title: "새해 복 많이 받으세요",
        client: "Try to 신감독",
        image: "https://img.youtube.com/vi/Di-6xXKzmN8/hqdefault.jpg",
        duration: "3:15",
        videoType: "youtube",
        youtubeUrl: "https://www.youtube.com/watch?v=Di-6xXKzmN8",
        videoUrl: "",
      },
      {
        id: "yt-J3MjM6o1YcA",
        category: "유튜브",
        title: "휴식이 필요해요",
        client: "Try to 신감독",
        image: "https://img.youtube.com/vi/J3MjM6o1YcA/hqdefault.jpg",
        duration: "3:27",
        videoType: "youtube",
        youtubeUrl: "https://www.youtube.com/watch?v=J3MjM6o1YcA",
        videoUrl: "",
      },
      {
        id: "yt-qjtuSLL9aHA",
        category: "유튜브",
        title: "잘하는 일? 해야하는 일? 하고 싶은 일? 으악!!",
        client: "Try to 신감독",
        image: "https://img.youtube.com/vi/qjtuSLL9aHA/hqdefault.jpg",
        duration: "5:14",
        videoType: "youtube",
        youtubeUrl: "https://www.youtube.com/watch?v=qjtuSLL9aHA",
        videoUrl: "",
      },
      {
        id: "yt-vEqr4PmGaE8",
        category: "유튜브",
        title: "특별한 듯, 특별하지 않은 그런 날",
        client: "Try to 신감독",
        image: "https://img.youtube.com/vi/vEqr4PmGaE8/hqdefault.jpg",
        duration: "2:54",
        videoType: "youtube",
        youtubeUrl: "https://www.youtube.com/watch?v=vEqr4PmGaE8",
        videoUrl: "",
      },
      {
        id: "yt-06RQLqc8Ouk",
        category: "유튜브",
        title: "여유가 없는 사람들에게",
        client: "Try to 신감독",
        image: "https://img.youtube.com/vi/06RQLqc8Ouk/hqdefault.jpg",
        duration: "4:22",
        videoType: "youtube",
        youtubeUrl: "https://www.youtube.com/watch?v=06RQLqc8Ouk",
        videoUrl: "",
      },
      {
        id: "yt-Jbgg23aH5uA",
        category: "유튜브",
        title: "난 내가 핵펀치인줄 알았지...",
        client: "Try to 신감독",
        image: "https://img.youtube.com/vi/Jbgg23aH5uA/hqdefault.jpg",
        duration: "7:06",
        videoType: "youtube",
        youtubeUrl: "https://www.youtube.com/watch?v=Jbgg23aH5uA",
        videoUrl: "",
      },
      {
        id: "yt-e32PaSeer84",
        category: "유튜브",
        title: "출근하는 모든이들에게",
        client: "Try to 신감독",
        image: "https://img.youtube.com/vi/e32PaSeer84/hqdefault.jpg",
        duration: "3:55",
        videoType: "youtube",
        youtubeUrl: "https://www.youtube.com/watch?v=e32PaSeer84",
        videoUrl: "",
      },
      {
        id: "yt-75ZBzPn4V-U",
        category: "유튜브",
        title: "꾸반성!!!!!",
        client: "Try to 신감독",
        image: "https://img.youtube.com/vi/75ZBzPn4V-U/hqdefault.jpg",
        duration: "6:10",
        videoType: "youtube",
        youtubeUrl: "https://www.youtube.com/watch?v=75ZBzPn4V-U",
        videoUrl: "",
      },
      {
        id: "yt-9x9gPbOztEo",
        category: "유튜브",
        title: "영상PD의 영상일지",
        client: "Try to 신감독",
        image: "https://img.youtube.com/vi/9x9gPbOztEo/hqdefault.jpg",
        duration: "2:22",
        videoType: "youtube",
        youtubeUrl: "https://www.youtube.com/watch?v=9x9gPbOztEo",
        videoUrl: "",
      },
      {
        id: "yt-XHajxfYZV2U",
        category: "유튜브",
        title: "20년 우정의 가평여행",
        client: "Try to 신감독",
        image: "https://img.youtube.com/vi/XHajxfYZV2U/hqdefault.jpg",
        duration: "4:11",
        videoType: "youtube",
        youtubeUrl: "https://www.youtube.com/watch?v=XHajxfYZV2U",
        videoUrl: "",
      },
      {
        id: "yt-ej93tu7_Eyg",
        category: "유튜브",
        title: "[TTD] 밀실스튜디오 대표님",
        client: "Try to 신감독",
        image: "https://img.youtube.com/vi/ej93tu7_Eyg/hqdefault.jpg",
        duration: "7:21",
        videoType: "youtube",
        youtubeUrl: "https://www.youtube.com/watch?v=ej93tu7_Eyg",
        videoUrl: "",
      },
      {
        id: "yt-W-fabVPm7L8",
        category: "유튜브",
        title: "Try To Cover_Ep01 강승호 (정준일-푸른끝)",
        client: "Try to 신감독",
        image: "https://img.youtube.com/vi/W-fabVPm7L8/hqdefault.jpg",
        duration: "6:03",
        videoType: "youtube",
        youtubeUrl: "https://www.youtube.com/watch?v=W-fabVPm7L8",
        videoUrl: "",
      },
      {
        id: "yt-A9vjA5ocqTo",
        category: "유튜브",
        title: "[단편영화] 무제",
        client: "Try to 신감독",
        image: "https://img.youtube.com/vi/A9vjA5ocqTo/hqdefault.jpg",
        duration: "21:26",
        videoType: "youtube",
        youtubeUrl: "https://www.youtube.com/watch?v=A9vjA5ocqTo",
        videoUrl: "",
      },
      {
        id: "yt-arr1O4uFkuo",
        category: "유튜브",
        title: "[대구 경북 휴게소 음식 먹방]  경부고속도로에서 뭐먹을래?",
        client: "Try to 신감독",
        image: "https://img.youtube.com/vi/arr1O4uFkuo/hqdefault.jpg",
        duration: "2:01",
        videoType: "youtube",
        youtubeUrl: "https://www.youtube.com/watch?v=arr1O4uFkuo",
        videoUrl: "",
      }
] as const;
